[global]
author=["technos-fpga"]

[parse]
sourcefile=[ "shadfrce.cpp" ]
rename = [
    { setname="shadfrce",  name="Shadow Force (FF, Technos, 1993)" },
    { setname="shadfrceu", name="Shadow Force (FF, Technos, 1993, US v2)" },
    { setname="shadfrcej", name="Shadow Force - Henshin Ninja (FF, Technos, 1993, Japan v2)" },
]

skip.setnames = [ "shadfrceu" ]

[buttons]
names = [
    { machine="shadfrce", names="Punch,Jump,Special" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
regions = [
    { name="maincpu",  width=16, reverse=true },
    { name="tiles",    start="JTFRAME_BA1_START" },
    { name="audiocpu", start="SND_START" },
    { name="oki",      start="PCM_START" },
    { name="chars",    start="CHAR_START" },
    { name="sprites",  start="JTFRAME_BA3_START", width=32, parts=[
        { name="32j8-0.32", crc="201bebf6", map="0001" },
        { name="32j7-0.25", crc="bcb37922", map="0010" },
        { name="32j6-0.24", crc="6cde8ebe", map="0100" },
        { name="32j5-0.13", crc="600026b5", map="1000" },
    ] },
]
order = [ "maincpu", "tiles", "audiocpu", "oki", "chars", "sprites" ]
